### ISSUE TITLE
Support SNORM formats

### ISSUE THREAD

**Issue by darksylinc** [Microsoft/DirectXTex#11]
Texconv will fail to load formats such as U8V8, U16V16 (R8G8_SNORM & R16G16_SNORM in D3D10 lingo).

Looking at dds files with these formats, it appears that they're exactly the same as their unsigned counter parts (e.g. R8G8_UNORM, R16G16_UNORM) except that the 'flags' member of the DDS_PIXELFORMAT structure has the DDPF_RGB bit unset, and the undocumented bit 0x00080000 set instead.

**Comment by darksylinc** [comment]
I'm uploading U8V8 & U16V16 samples for reference. Both are set to +1.0; +1.0 which should show yellow (if B <= 0) or white (if B = 1)

http://www.mediafire.com/download/18b4dx8cgdfhhvq/texconv_UV8V8_U16V16.7z

**Comment by walbourn** [comment]
Can you please attach some example ``DDS`` files here? Also, do you have any 'real-world' examples rather than just test ones with a single value?

**Comment by AllianceDarkSylinc** [comment]
Sure, here is a better real world test:
https://www.mediafire.com/?cgu0auubfcdtvge
It's a normal map in U8V8 format, and for comparison its reference in RGB.

It was somewhat popular back then in DX9 days for normal mapping when BC5 was not around and DXT5 hack provided too many artifacts or was too cumbersome; and certain GPU HW could save you the unsigned to signed conversion in the shader.

**Comment by walbourn** [comment]
Note that the `` DDPF_BUMPDUDV`` (``0x00080000`` ) and ``DDPF_BUMPLUMINANCE`` (``0x00040000`` ) are for old specialized bump-mapped formats which don't really apply to modern Direct3D . I'm curious was to your usage case for DDS files in this legacy format.

**Comment by AllianceDarkSylinc** [comment]
Interesting. They were likely associated with normal mapping since that was the primary use for U8V8 format.

But these formats were still useful for tangent space normal mapping (since they were signed formats) and not just the old fixed function bump mapping. These formats map 1:1 to R8G8_SNORM & R16G16_SNORM

There was even a CxU8V8 format that would automatically calculate B = 1 - sqrt( R*R + G*G ) for you. However it was discouraged by vendors because they said they just used a 32-bit texture instead of doing the calculation on the fly; so it was better to do it manually in the shader with a U8V8.

They're quite convenient even today since they can work interchangeable with BC5 (both are signed, both map to RG channels); though admittedly this feature is most useful in texconv for converting old uncompressed assets into BC5.

**Comment by walbourn** [comment]
I can see the following mappings working, but I only have test content for one case. If you can dig up more, that would be a great help:

* ``D3DFMT_V8U8`` -> ``DXGI_FORMAT_R8G8_SNORM``
* ``D3DFMT_Q8W8V8U8`` -> ``DXGI_FORMAT_R8G8B8A8_SNORM``
* ``D3DFMT_V16U16`` -> ``DXGI_FORMAT_R16G16_SNORM``

> Note I handle ``D3DFMT_Q16W16V16U16`` (which was stored as a FourCC of 110) as ``DXGI_FORMAT_R16G16B16A16_SNORM``

I don't think there's a sensible general conversion for the old ``DDPF_BUMPLUMINANCE`` formats, and there's no DXGI equivalent for a mixed format like ``D3DFMT_A2W10V10U10``. Xbox One does have  ``DXGI_FORMAT_R10G10B10_SNORM_A2_UNORM`` which would work for ``D3DFMT_A2W10V10U10``.

**Comment by AllianceDarkSylinc** [comment]
Indeed to all of that. There are no more signed formats as far as I know, except for CxU8V8 which is a little more annoying to support because it needs to map to DXGI_FORMAT_R8G8B8A8_SNORM and then manually fill the blue channel with 1 - sqrt( r*r + g*g )
Also it was barely used to be bothered.

I don't see where DDPF_BUMPLUMINANCE in being used, and those mixed formats don't really have a DXGI equivalent (except the Xbox One case you mention).

If you want/need more DDS test cases let me know, I have more.

**Comment by walbourn** [comment]
I think ``D3DFMT_V8U8`` is covered. A real world case for ``D3DFMT_V16U16`` would be great, as would one for ``D3DFMT_Q8W8V8U8`` and ``D3DFMT_A2W10V10U10`` if you can dig one up.

If you happen to have a real-world test of ``D3DFMT_CxV8U8`` I can look at that conversion.

**Comment by walbourn** [comment]
Fixed with commit a121bc5c312dcfb6a237d559e8855b5b50305ef8

**Comment by darksylinc** [comment]
Whoa!!! That was fast!!! Thank you!
