### ISSUE TITLE
BC5 compression broken?

### ISSUE THREAD

**Issue by feliwir** [Microsoft/DirectXTex#12]
Hello, when compressing to BC5_UNORM or BC5_SNORM there seems to be a problem with the generated dds. It can't be opened by any tool. Ddsview is able to open it, but it looks completly broken:
![image](https://cloud.githubusercontent.com/assets/2104576/12859784/ca283b98-cc58-11e5-95f4-f331536b72f1.png)

(it became all yellowish)

**Comment by walbourn** [comment]
If you render BC4 or BC5 as a standard RGB texture, it will end up looking odd because those formats only define 2-channels, which map to R and B (i.e. no green channel). By basic [additive color](https://en.wikipedia.org/wiki/Additive_color), that would be yellow.

You can view it with Visual Studio 2012-2015 as well, which would also make it appear 'yellow' for the same reasons.

> The DXTex tool in the legacy DirectX SDK was never updated for DirectX10 or DirectX11. That includes BC4, BC5, BC6, BC7, and anything that uses the 'DX10' header extension. That's why [this issue](https://github.com/Microsoft/DirectXTex/issues/2) tracks and I've been hoping to get to it for years now.
