### ISSUE TITLE
How can i load a DX12 Texture?

### ISSUE THREAD

**Issue by JavierMaura** [Microsoft/DirectXTex#120]
What to do from here?

	bool TextureBase::Load(const wchar_t *lpCmdLine)
	{
		TexMetadata mdata;
		HRESULT hr = GetMetadataFromDDSFile(lpCmdLine, DDS_FLAGS_NONE, mdata);
		if (FAILED(hr))
		{
			wchar_t buff[2048] = {};
			
			swprintf_s(buff, L"Failed to open texture file\n\nFilename = %ls\nHRESULT %08X", lpCmdLine, hr);
			
			OutputDebugString(buff);

			return false;
		}
		
		UINT g_iMaxIndex;

		if (mdata.dimension == TEX_DIMENSION_TEXTURE3D)
		{
			if (mdata.arraySize > 1)
			{
				wchar_t buff[2048] = {};
				swprintf_s(buff, L"Arrays of volume textures are not supported\n\nFilename = %ls\nArray size %zu", lpCmdLine, mdata.arraySize);
				OutputDebugString(buff);
				return 0;
			}

			g_iMaxIndex = static_cast<UINT>(mdata.depth);
		}
		else
		{
			g_iMaxIndex = static_cast<UINT>(mdata.arraySize);
		}

		ScratchImage image;
		hr = LoadFromDDSFile(lpCmdLine, DDS_FLAGS_NONE, &mdata, image);
		if (FAILED(hr))
		{
			wchar_t buff[2048] = {};

			swprintf_s(buff, L"Failed to load texture file\n\nFilename = %ls\nHRESULT %08X", lpCmdLine, hr);

			OutputDebugString(buff);

			return 0;
		}

		// Special case to make sure Texture cubes remain arrays
		mdata.miscFlags &= ~TEX_MISC_TEXTURECUBE;
// *****************************************************************************		
// I have the Texture in image, but....HOW to store it on a DX12 Buffer?
// *****************************************************************************		

Thanks

**Comment by walbourn** [comment]
There are various ways to perform the upload of course, some more efficient than others.

In the DirectXTex library, you can make use of the functions ``CreateTexture`` or ``CreateTextureEx`` which will create the committed resource, then ``PrepareUpload`` to set up a vector of ``D3D12_SUBRESOURCE_DATA`` which points into the loaded ``Image``. From there you can create a UPLOAD resource and then use the [D3DX12](https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3DX12) utility header's function ``UpdateSubresources``. This is all covered in the [wiki](https://github.com/Microsoft/DirectXTex/wiki/CreateTexture#directx-12-1).

A more efficient solution is to use the [DirectX Tool Kit for DX12](https://github.com/Microsoft/DirectXTK12/wiki) instead of DirectXTex which has light-weight texture loaders that utilize the ``ResourceUploadBatch`` helper. This can perform uploading of several textures in a batch, as well as supporting DirectCompute-based auto-generation for mipmaps.

> If you are confused as to why I've implemented two different ways to load textures, see [this blog post](https://blogs.msdn.microsoft.com/chuckw/2012/05/04/direct3d-11-textures-and-block-compression/).

**Comment by JavierMaura** [comment]
Great!!! I have it working now!! 
Not, it's time for Generating MipMaps.... :)
