### ISSUE TITLE
sepalpha seems to not behave correctly when converting to BC1_UNORM

### ISSUE THREAD

**Issue by FlorianLunaWild** [microsoft/DirectXTex#154]
Hello,
I am trying to convert a tga file that contains alpha information that is not transparency info. When converted, the rgb data is set 0 where the alpha channel is set to 0. I was not expecting that when using -sepalpha flag which seems to be used to avoid those kind of issues. Maybe I don't get it correctly. Here is the full command I use 
 texconv.exe -nologo -sepalpha -dx10 -m 8 -f BC1_UNORM myfile.tga.

Best regards,
Florian Luna

**Comment by walbourn** [comment]
Can you provide a link to the ``TGA``?

Normally the RGB is 0 when alpha is 0 due to premultiplied alpha. Is the image straight-alpha?

**Comment by FlorianLunaWild** [comment]
Hello,
Thanks for replying and sorry for my late answer. I was not available until this morning. Here is a link to the file : https://drive.google.com/file/d/1_JHHGV6f5l_-mAn3PjQJKe9n-5NwzWf7/view

I thought that the sepalpha tag was disabling the premultiplied alpha because the alpha was used to encode other data. I am probably wrong!

**Comment by walbourn** [comment]
OK, so the purpose of ``-sepalpha`` is indeed to handle the case where you have uncorrelated data in the alpha-channel due. WIC normally uses premultipled-alpha internally so if your data isn't alpha in the alpha channel, it can indeed destroy the data in the RGB channel.

The issue you are having here is not that. The issue is that BC1_UNORM doesn't have any way to encode the RGB data for transparent pixels. The values are 0,0,0 in RGB where the alpha is transparent because that's all that format can encode. You need to use BC2, BC3, or BC7 instead if you want to have RGB data as well as alpha data.

**Comment by FlorianLunaWild** [comment]
thanks for the answer, that makes perfect sense!
