### ISSUE TITLE
Floating point volume textures compressed as DXT1 come out black

### ISSUE THREAD

**Issue by redorav** [microsoft/DirectXTex#164]
Hi,

I'm having issues with volume textures that are floating point but come out black when trying to compress to DXT1. I'm attaching an example image (rename extension to .dds)

The command line is very simple 

> texconv.exe -f DXT1 -sx "_BC" -ft DDS -m 1 -nologo -o C:\MyFolder Original.dds

![Original](https://user-images.githubusercontent.com/700032/73448525-f41dd400-4358-11ea-9962-c8349cfd4a11.png)

**Comment by walbourn** [comment]
Using the ``texdiag`` tool in ``analyze`` mode, I get this output:

```
Result slice   0, mip   0:
	  Minimum - (0.214469 0.135705 0.093044 0.214469)
	  Average - (0.350606 0.332963 0.388020 0.350606)
	  Maximum - (0.461166 0.499991 0.670765 0.461166)
	 Variance - (5.291549 11.871540 34.570198 5.291549)
	  Std Dev - (2.300337 3.445510 5.879642 2.300337)
	Luminance - 0.484935 (maximum)
```

The key thing to note is the fourth value which is alpha which has the same data as the red channel.

DXT supports 1-bit alpha. The default alpha threshold value for [Compress](https://github.com/microsoft/DirectXTex/wiki/Compress) is 0.5, which means all those pixels are encoded as transparent instead of opaque. Hence the color is 'black'.

**Comment by redorav** [comment]
I see, this is a side-effect of me swapping a RWTexture<float4> for a RWTexture<float3> in a shader which generates the texture, DX11 will just write the x value there. Thanks for looking into it, other than the convenience of a threshold I think there's no real bug here and I can fix it on my end.

**Comment by walbourn** [comment]
Sounds good. New switch in [this commit](https://github.com/microsoft/DirectXTex/commit/0dd4cb9ca2d9bce83846498bd81b435f904506c5).
