### ISSUE TITLE
Texconv: Add flag to control case of file extension

### ISSUE THREAD

**Issue by rminderhoud** [microsoft/DirectXTex#170]
Hello,

I was wondering whether it would be possible/feasible to add a flag to `texconv` to control the case of the output file extension. Currently it outputs the extension in all caps (e.g. `output.DDS` or `output.PNG`, regardless of the case of the input file). It'd be great if it could match the case of the input file or otherwise be control this with a flag.

**Comment by walbourn** [comment]
Hmm... Windows is generally a case-insensitive file system, but I know there are issues with git and of course cross-system.

How exactly would the logic work?

* If the original filename is all lower case, use ``dds``
* If the original filename is all upper case, use ``DDS``
* Otherwise pick based on a setting?

How about instead having a flag to force the resulting filename to all lower-case? ``-tolower``?

**Comment by rminderhoud** [comment]
It's true that windows is case-insensitive but when scripting through file names or working with assets across platforms then it can be more problematic. In my use case I'm simply using `texconv` in a script and as such it was just more of a "surprise" to have the files output with a different cased extension. Right now I just change the extension afterwards as a workaround to keep my converted assets consistent with the source.

Current behavior:
- `texconv.exe mytex.png` => `mytex.DDS`

Any of the above solutions would work although I think the automatic casing would be the most intuitive? Although an explicit flag would be fine if it's simpler to implement.

In my opinion, this would be the ideal behavior:
- `texconv.exe mytex.png` => `mytex.dds`
- `texconv.exe mytex.PNG` => `mytex.DDS`
- `texconv.exe MYTEX.png` => `MYTEX.dds`
- `texconv.exe MYTEX.PNG` => `MYTEX.DDS`

I.E. the new extension should match the case of the old extension.

**Comment by walbourn** [comment]
So: If the original is all lower-case, use all lower-case.

If the original is all upper-case, use all upper-case.

If it's something else I'll stick with all upper-case.

Does that work?

How does the idea of having a way to force the output to all lower case (``-tolower``)?

**Comment by rminderhoud** [comment]
Honestly both options sound great, I'm being a bit of a choosy beggar here so whichever is the easiest to implement and whichever option you prefer I will be happy with.

**Comment by walbourn** [comment]
All my tools now have a ``-l`` switch to force lower case on the output filename & path:

DirectXMesh:
https://github.com/microsoft/DirectXMesh/commit/cde949addd61e62aafd688cc62527f14a9bf0532

DirectXTex:
https://github.com/microsoft/DirectXTex/commit/e169033b6012ef0a12ea42d2008e7051d2263fa6

DirectXTK:
https://github.com/microsoft/DirectXTK/commit/45b0f9fbb4afea1d7a3efbeb743a8e6676140bf3

UVAtlas:
https://github.com/microsoft/UVAtlas/commit/2685ba9175e4287da797e3460a036c9e8ff865c5

**Comment by rminderhoud** [comment]
Thank you so much!

**Comment by walbourn** [comment]
No problem. git is fussy about case anyhow, so might as well get it fixed.

**Comment by hugoam** [comment]
Hmmm, I'm not sure how this issue can considered solved.
Currently `MyFile.dds` will end up converted to either `MyFile.DDS` (which is bad, and I'm wondering for which reason we chose to be one of 1% of apps that consider uppercase extension to be the default), or `myfile.dds` if using the `-l` option, which is also bad.
Saying that Windows is case insensitive is an over simplification. It's not completely case insensitive, if it was there wouldn't be an issue here :)
Is it thinkable to have a proper fix to this issue in the future ?

**Comment by walbourn** [comment]
What exactly would you expect here then? (a) check to see if the input is all-uppercase, use that (b) check to see if the input is all lower-case, use that?

**Comment by hugoam** [comment]
I would expect to have a sensible default, so lowercase by default, which is the most common pattern used overall by far. Then if you really need a switch to control this behavior, an optional switch to match the input case (lowercase -> lowercase, uppercase -> uppercase, mixed -> fallback on default which is lowercase)

I understand this would break the existing behavior, but the existing behavior simply does not make sense to me

**Comment by walbourn** [comment]
Thanks for the feedback and pushing me on this one a bit...

I went back and looked at the original DirectX SDK texconv tool source code and it defaulted to lower-case when it added an extension. This is my bug because I was being clever with ``g_pSaveFileTypes`` to avoid a nasty, difficult to maintain switch statement in the original source. This behavior was therefore a side-effect rather than an intentional choice.

Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/2324cb0dc49ddce9fe06ee3c1b436901f0507e72).

All I can say is "my bad" and sorry for ignoring this quirk for 10 years.
