### ISSUE TITLE
BC5 seems to swap red and green channels

### ISSUE THREAD

**Issue by thomasandersen** [microsoft/DirectXTex#201]
Hi 

When running this command

```
./texconv.exe specular.png -y -f BC5_SNORM
```

the result image seems to have the red and green channel 'swapped'.  
Please see the following images for a better information

Same result when using the BC5_UNORM

Original / png source
![Original](https://user-images.githubusercontent.com/194093/97873049-5a37ed00-1d17-11eb-8006-6e085f318d85.jpg)

Result / dds
![Result](https://user-images.githubusercontent.com/194093/97873066-602dce00-1d17-11eb-8cad-1563b545a2c9.jpg)

Am I missing something here or is this expected? I've tried to search for answers, but no success so far.

Version info:
Microsoft (R) DirectX Texture Converter [DirectXTex] Version 2020.9.30.1

Let me know and I can provide the source image if needed.

Best regards,
Thomas Andersen

**Comment by walbourn** [comment]
Can you attach your ``specular.png`` file?

**Comment by thomasandersen** [comment]
Source file

![specular_source](https://user-images.githubusercontent.com/194093/97969044-c40bd180-1dbf-11eb-91e0-80fa05db9bb2.png)

**Comment by thomasandersen** [comment]
Components values for the source

R: Value .6
G: BW/Gloss map
B: Value 0

**Comment by walbourn** [comment]
I'm not sure what you are using to view the ``DDS`` file, but in Visual Studio it's showing the expected result.

```
Red is solid grey
Green has the gloss map
Blue is solid grey
Alpha is solid white (default opaque value because BC5 has no alpha channel)
```

The point of confusion here is how the image is converted from UNORM to SNORM and then back to UNORM for viewing. Remember that ``PNG`` only encodes UNORM (0-255) values which is 0..1 in float, but you are using ``BC5_SNORM`` which encodes -127 to 127 which is -1..1 float in a lossy manner.  The reason the Blue channel looks grey is that the decompress converted ``BC5_SNORM`` to to ``R8G8_SNORM`` and then to ``R8G8B8A8_UNORM`` to view it. That SNORM to UNORM conversion implicitly converts the range -1..1 to 0..1 via a ``x * 0.5 + 0.5`` i.e. an "x2 bias".

If you used ``BC5_UNORM`` instead, you get consistent pixels with no "x2 bias". Note that DirectXTex (and Visual Studio's viewer) will set the alpha channel to all opaque instead of all zero when converting from a non-alpha format to alpha one.

Alternatively, since you are starting with unsigned data and using it as signed, you may want to use ``-x2bias`` to force the original ``UNORM`` to ``SNORM`` conversion to use an "x2 bias" instead of "clamping".

> If you were using a height-map and wanted a normal map, you can use ``-nmap``. If the BC5 DDS was a 2 channel normal-map, you can use ``-reconstructz`` to get a sensible B value. If you wanted to invert the Y value due to OpenGL vs. Direct3D conventions in normal maps, use ``-inverty``.

See [the wiki](https://github.com/microsoft/DirectXTex/wiki/Texconv).
