### ISSUE TITLE
Incorrect default gamma when saving as PNG

### ISSUE THREAD

**Issue by dtzxporter** [microsoft/DirectXTex#220]
https://github.com/Microsoft/DirectXTex/blob/master/DirectXTex/DirectXTexWIC.cpp#L655

I believe this number should be 45455, according to the specifications as well. When using 100000 image processing utilities that respect the gamma chunk display an incorrect value (Photoshop / Paint.NET do not respect this and ignore it completely so it looks fine) But Windows 10 photo viewer will show the incorrect image. When set to 45455 (using unsigned formats) The image appears correct in other tools that respect that chunk, and stays working in photoshop/paint.net.

**Comment by walbourn** [comment]
I'm specifically setting a 'linear' gamma in the case that that the input format is not ``_SRGB`` either by virtue of the DXGI_FORMAT or the ``WIC_FLAGS_FORCE_SRGB`` control flag.

The ``45455`` value in the spec is for gamma 2.2 which is SRGB, which is indicated with the ``sRGB`` chunk instead of with a ``gAMA`` chunk.

**Comment by dtzxporter** [comment]
Interesting, so you're saying that for PNG I should always give it SRGB data then? Even when the input was BC1_UNORM -> transcoded to DXGI_FORMAT_B8G8R8A8_UNORM? Because what I'm currently doing is transcoding the BC1 to a format that's compatible with the WIC formats UNORM -> UNORM, then saving.

**Comment by walbourn** [comment]
There's been a constant challenge with sRGB colorspace vs. DXGI_FORMAT. Most formats default to sRGB even when it's not, and I really only know for sure if the format is a ``DXGI_FORMAT_*_SRGB`` format like ``BC1_UNORM_SRGB`` on input. I can't tell if you intended ``BC1_UNORM`` to be linear or sRGB.

And of course, many engines render all UNORM content assuming it's SRGB.

WIC always default to putting an sRGB chunk into PNGs it writes, which for linear data is wrong.

I've added a plethora of fixes and flags over the years to try to manage this since it depends heavily upon the content and context:

https://github.com/microsoft/DirectXTex/wiki/Filter-Flags#color-space

https://github.com/microsoft/DirectXTex/wiki/WIC-I-O-Functions#color-space

**Comment by dtzxporter** [comment]
Thanks! I think I'll just end up modifying it to suite my needs at this point. So I'm fine with closing this issue.

**Comment by walbourn** [comment]
You can probably achieve whatever behavior you with with one of the many flags. If not, please let me know what behavior you believe would be useful to add.

Thanks!

**Comment by walbourn** [comment]
Note that WIC will also write ``gAMA = 45455`` whenever you write the ``sRGB`` chunk per the spec for back-compat.
