### ISSUE TITLE
Dark scales of grey becomes greenish after conversion

### ISSUE THREAD

**Issue by hugoam** [microsoft/DirectXTex#221]
Hello ! 

We've got an issue where converting dark images yields aberrant colors that did not exist in the input (but not obvious, since those are very dark tones)
I can't exactly pinpoint whether this is a texconv issue, or an issue inherent to the BC codec which we can't do anything about ?
But if it is, I don't really understand how BC could reasonably be used so widely, so something doesn't quite fit here

The original .tif image

![image](https://user-images.githubusercontent.com/9502098/109655534-a9761900-7b63-11eb-9f26-e1b6c1ca8733.png)

The resulting BC3_UNORM output, where the dark grey/brown in some places suddenly get a greenish hue that comes from nowhere

![image](https://user-images.githubusercontent.com/9502098/109655483-9d8a5700-7b63-11eb-826d-9635b13630d3.png)

I've tried a range of command line options so far, but none have solved the issue
Any help would be greatly appreciated !

**Comment by walbourn** [comment]
This is likely an artifact of the BC algorithm. Remember that in BC1-3, the RGB end-points are 5:6:5 which tends to make things 'greenish' in edge cases.

If you are targeting Feature Level 11.0 or better hardware, BC7 is a better choice.

Otherwise, you can try ``-bc:u`` to use a non-perceptually weighted evaluation, although perhaps you already tried that.

**Comment by walbourn** [comment]
Another possible work-around is for me to implement 'custom' weights per [this issue](https://github.com/microsoft/DirectXTex/issues/84)

**Comment by walbourn** [comment]
I don't know if your particular image could benefit from this, but there's also another possible optimization for cases where the 4x4 block all contains the same pixel value. See [this issue](https://github.com/microsoft/DirectXTex/issues/223)

**Comment by Bxaa** [comment]
This issue with all texconv bc1-3 compression. I tried NVTT and other noname dds compressors - no such issue
Texconv just unuseful for bc1-3 compression while this issue not fixed
Exampless:
Bc_1 texconv\nvtt\uncompressed(for test)
https://drive.google.com/file/d/1PRPPyTCNH5KZrQCvwV1aGTh0KiN-TCyn/view?usp=sharing

**Comment by walbourn** [comment]
I see it with this latest test case. I don't see in legacy D3DX9 compression.

**Comment by walbourn** [comment]
NVTT has the [single color](https://github.com/microsoft/DirectXTex/issues/223) optimization, so that's something I should do sooner than later. That said, this is *mostly* for performance of compression more than correctness.

That said, legacy D3DX9 texconv and dxtex do *not* result in the same 'green-ness' DirectXTex texconv seems to produce. I notice the enabling the BC1-3 dithering (``-bc d``) seems to help. I'm trying to see if that's the difference here are not.

**Comment by Bxaa** [comment]
Thx, **walbourn** 
I'll try and report

**Comment by walbourn** [comment]
I'll keep looking to see if there's some other difference between the legacy D3DX9 and DirectXTex DXTn compressor that could account for thi.

**Comment by walbourn** [comment]
Looking closely at the D3DX9 compressor results, it really does look to me like dithering is the key difference, so ``-bc d`` should be the answer.

In fact, from a "root-mean-square error" metric, the result of the modern texconv with ``-bc d`` is better (PSNR 44.663095 dB) vs. the older D3DX9 compressor (PSNR 42.847420 dB). Without dithering, the new texconv has the same as the old D3DX9 PSNR 42.847420 dB). Of course, PSNR isn't the same as a perceptual difference metric.
