### ISSUE TITLE
Static code analysis warnings in DirectXTex

### ISSUE THREAD

**Issue by jakrams** [microsoft/DirectXTex#224]
The SAL annotations on some functions are either incorrect, or the code doesn't behave as advertised. Since I don't know which one it is, I'll just forward the static code analysis warnings that we are seeing when building DirectXTex:

```
DirectXTexConvert.cpp(1610,14): error 6101: : Returning uninitialized memory '*pDestination'. A successful path through the function does not set the named _Out_ parameter. 

DirectXTexConvert.cpp(3905,14): error 6101: : Returning uninitialized memory '*pDestination'. A successful path through the function does not set the named _Out_ parameter. 

d3dx12.h(2418,62): error 6001: : Using uninitialized memory '*pParameters_1_0.DescriptorTable.pDescriptorRanges'
```

This is with the release from January 9, 2021.

**Comment by walbourn** [comment]
Thanks. I've tried many variations of SAL annotations on those functions in Convert to resolve the ``/analyze`` warnings. It's a macro-built case statement, and it's huge, so I've had limited success. If you have any suggestions other than forcing an initial memset of the buffer, I'm open to hearing them--although I suppose I could add that memset guarded by ``__PREFAST__`` but that's a bit quirky.

The D3DX12.H issue is also a known issue. I'll double-check on the bug status for that one.

**Comment by walbourn** [comment]
The D3DX12.H issue is tracked [here](https://github.com/microsoft/DirectX-Headers/issues/5)

**Comment by jakrams** [comment]
Haha, yes I've actually added a memset to our internal copy to silence the warning for now.

Reading up on SAL again, it looks correct to me, at least how I understand it:
https://docs.microsoft.com/en-us/cpp/code-quality/annotating-function-parameters-and-return-values?view=msvc-160

However, this annotation says it writes "up to 'size'" elements. Maybe the compiler just needs to see at least a single byte write (instead of a full memset) ?

I wouldn't mind the __PREFAST__ option either, at least that documents the reasoning behind the initial write to the buffer.

**Comment by walbourn** [comment]
Thanks for prodding me on this issue... I had kept the library clean for years, then all the *C++ Core Guidelines* checker stuff introduced a lot of noise, and I had basically reduced it down to just these few warnings and called it good enough.

The new VS 2019 "Run Code Analysis on File" also made the iteration time on finding it a lot less painful :)

It does seem like a bug of some kind the analyzer or the expressions are just a little too messy for it to figure out. The only legitimate way I can see for it to hit this condition is if ``count == 0``, but even eliminating that possibility doesn't make it realize there's always at least one pixel written -or- an error is returned.

Writing a single byte to ``pDestination`` does seem to make the warning go away, but that's because I used ``_Out_write_bytes_`` instead of ``_Out_write_bytes_all_``.

**Comment by jakrams** [comment]
I know how you feel. We also spend a lot of time on reviewing and trying to fix warnings that are often false positives. Since there doesn't seem to be a correct fix, I wouldn't even mind if you don't fix it at all. I'll just keep in mind that I need to patch it again, next time I update the library. We have the same situation with other libraries.

**Comment by walbourn** [comment]
Went with [this commit](https://github.com/microsoft/DirectXTex/commit/77f1a6fc86524e9f096b599b097ec4dda725a297)

**Comment by jakrams** [comment]
Thank you very much :)

**Comment by walbourn** [comment]
D3DX12 warning fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/27b581cbf48fdd059cc06a368933afa3562c821d)
