### ISSUE TITLE
Texdiag error 80070032 (ERROR_NOT_SUPPORTED) with 8BIT-LUMA(?) DDS

### ISSUE THREAD

**Issue by Bxaa** [microsoft/DirectXTex#230]
Example DDS (dds is correct):
https://drive.google.com/file/d/1azGDJrURDInNlCYfIYMmoWCjPGeWgUxR/view?usp=sharing

**Comment by walbourn** [comment]
Looks like the same problem again:

```
DDS C:\Users\chuckw\Downloads\8bit_luma\8bit_luma.dds
Flags 0002100f: CAPS HEIGHT WIDTH PITCH PIXELFORMAT MIPMAPCOUNT
1024 x 1024
Pitch: 1024
Mipmap count: 11
Surface flags: 00401008: COMPLEX TEXTURE MIPMAP
PIXELFORMAT: 00000040: RGB
bitCount 8
R: 000000ff G: 00000000 B: 00000000 A: 00000000
Reserved area:
   00000000 00000000 00000000 00000000
   00000000 00000000 00000000 00000000
   00000000 3354564E 00000000
   00000000
nVidia Texture Tool extension present 'NVT3'
```

D3DX would write this as:

```
{ sizeof(DDS_PIXELFORMAT), DDS_LUMINANCE, 0,  8, 0xff, 0, 0, 0 };
```

Will add another alt

**Comment by walbourn** [comment]
Same thing would happen with 16bit luminance  with NVTT version 1:

```
{ sizeof(DDS_PIXELFORMAT), DDS_LUMINANCE, 0, 16, 0xffff, 0, 0, 0 };
```

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/5f22c7cc39241515f026269014678c157dc3dd9b)

Also fixed in:

https://github.com/microsoft/DirectXTK/commit/431955cce2a24e831b01583e0232300f5e5128d4
https://github.com/microsoft/DirectXTK12/commit/f620bb5fb6151f8bc8aa3c27139d684de161c893

**Comment by Bxaa** [comment]
Thx
