### ISSUE TITLE
Converting Opaque\Noalpha images to any Non-DDS formats produce image with blank alpha channel

### ISSUE THREAD

**Issue by Bxaa** [microsoft/DirectXTex#237]
texconv -ft png any.dds (any dds without alpha, include dds with forced disabled or removed alpha)
(while converting to png, tif, tga...)

Same issue with converting any image to non-dds formats
Example: while converting RGB png to tga output is RGBA (with blank alpha)

**Comment by walbourn** [comment]
Can you find a concrete example file?

**Comment by Bxaa** [comment]
DXT1
https://www95.zippyshare.com/v/y0A0LdKa/file.html
Reproduce:
texconv -ft png upperbodymale.dds

**Comment by Bxaa** [comment]
UPD:
https://github.com/castano/nvidia-texture-tools
No issue with dark scales, but broken dxt1 (loss pixels)
(nvcompress compress.cpp and nvtt)

**Comment by walbourn** [comment]
There's no DXGI format for '24bpp' (i.e. R8G8B8), so I don't use it at all when writing DDS files. Therefore, it must be promoted to R8G8B8A8_UNORM or B8G8R8A8_UNORM.

In theory it could be made ``B8G8R8X8_UNORM``, but since BGR formats were introduced in DXGI 1.1 instead of DXGI 1.0, I tended to prefer RGBA32.
