### ISSUE TITLE
DirectXTex.lib file missing

### ISSUE THREAD

**Issue by OceanJeff40** [Microsoft/DirectXTex#24]
Same Issue for texassemble compilation, missing .lib file.
Just curious if there are any other files that the compiler is going to look for AFTER this one is found, that may not have been uploaded to the repository.  Would be worth a double check of all appropriate files.
I was actually just looking for a .exe file, and found the source code and project files instead..........sigh
Jeff

**Comment by walbourn** [comment]
You likely opened up the texconv/texassemble vcxproj rather than the sln which would have build the DirectXTex library along with the tool using project-to-project references.

You can find the exe version of the tools prebuilt with the [release](https://github.com/Microsoft/DirectXTex/releases/tag/apr2016)
