### ISSUE TITLE
Metadata support in DDS format?

### ISSUE THREAD

**Issue by alecazam** [microsoft/DirectXTex#264]
How is metadata added to DDS?  I was switching to all KTX and KT2 files, and can store name-value pairs in sections that are near the header.  Most file formats like PNG, JPG have this facility.  This can store premul channels and ordering, types identifying height and sdf, rdo, pre and post swizzles, twiddled/tiled format for SVT, etc.  

When I convert images in my image tool kram from KTX to DDS then all of that metadata is lost.  I need to do this since many Windows tools only take PNG, JPG, or DDS files.  But I don't want to have to stuff all this metadata onto the filenames.  Especially on Windows, where filename length is still a problem.

**Comment by walbourn** [comment]
DirectDraw Surface (DDS) is intentionally a very simple format: It's just a container for Direct3D resources. With FOURCC codes, there have been variants created for special-purposes, but since the value of the format is that various tools support it, that's often more a 'hack' of expediency.

To date the only 'official' metadata expansion was the addition of the ``DX10`` FOURCC and extended header which was added to support ``DXGI_FORMAT`` values instead of using legacy DirectDraw PIXELFORMAT descriptions of formats. The lack of 'extension' support in DDS means that any changes to the format would break backward compatibility.

A number of developers have embedded DDS content within other files which contain additional metadata. Given that DDS is primarily intended as a 'runtime' format rather than an 'authoring' format, that's probably the better solution.

> The list of `DXGI_FORMAT` values is on [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format). It does not contain ETC, ASTC, or PVRTC formats as those are not supported by DirectX.

**Comment by alecazam** [comment]
I'd like to adopt Microsoft move to KTX or KTX2, if this format is truly not extendable.

**Comment by walbourn** [comment]
``DDS`` is the historical Direct3D texture format, and will be used and supported for a long time to come. One of the purposes of DirectXTex is to ensure the format's "canonical implementation" is an open source one rather than the closed source deprecated D3DX library.

Anyone is of course free to add DirectX support to the Khronos project if they so desire.

**Comment by walbourn** [comment]
There was a preview release of the Windows SDK headers that contained those DXGI_FORMAT values, but it was never released as Direct3D has never supported ASTC. I don't know if those values will ever be 'recycled', but you can probably count on them and use the "DX10" extended header in this way.

For ETC2/EAC, there has never been any intention to support those formats in Direct3D. That said, I have seen an old AMD tool that used a DDPIXELFORMAT FOURCC of "ETC ", so it would likely be 'safe' to add FOURCC values of "ETC2" and "EAC ". I wouldn't make up any DXGI_FORMAT values as those are more likely to collide with future changes.
