### ISSUE TITLE
why texconv.exe will quit when lock screen(win+L)? print : Failed to create D3D device

### ISSUE THREAD

**Issue by zhaoqingqing** [microsoft/DirectXTex#267]
hello, i have a problem,  i compress  a lot of tga  eg:5000 tga files to dds , when i press win+L to lock windows scree , texconv.exe  will quit ,print error：Failed to create D3D device

the other case is when the remote desktop is disconnect windows will  automatically locks the screen ,then texconv.exe also will quit and print error : Failed to create D3D device

how can i fix this bug ???
@walbourn

**Comment by walbourn** [comment]
What operating system version are you using?

**Comment by zhaoqingqing** [comment]
@walbourn  hi ,my os info:
win10 pro x64
verstion: 10.0.19042.1348
windows update patch: 20H2

**Comment by walbourn** [comment]
Are you selecting a specific adapter with ``-gpu``?

**Comment by zhaoqingqing** [comment]
hello, i am sorry,   I try many times ，found i use old version have this bug, when i update to new version ,is not happen.

but new version cant add args: -mf BOX_DITHER，in old version (dx9)，has this args ,mean:  -mf <filter>        mip filter

but our a old  game is run in dx9 , so our use old version.

in old version ,when lock screen program will exit and cmd msg is :  Failed to create D3D device

i will test new version can compatible with dx9  ,than you .

<hr>
not use args -gpu，my cmd is:

```
cmd = 'texconv -nologo -if TRIANGLE_DITHER -y -dx9 -m %d -f "%s" -o "%s" "%s"' % (mipCount, format, targetPath, texFile)
os.system(cmd)
```

new version:
``` shell
C:\Users\zhaoqingqing01>texconv
Microsoft (R) DirectX Texture Converter [DirectXTex] Version 2021.11.8.1
Copyright (C) Microsoft Corp.
```
<br/>
our use old version:

```
Microsoft (R) D3DX9 Texture Converter
Copyright (C) Microsoft Corp 2001. All rights reserved.
```

**Comment by walbourn** [comment]
Thank you for the additional information.

The legacy DirectX SDK contained ``texconv.exe`` which is the tool you are using. It was written using legacy Direct3D 9 and the deprecated D3DX9 library, and therefore has a number of known limitations. Legacy Direct3D 9 does not tolerate 'session 0' or 'secure desktop' well which is why you are encountering that failure.

The DirectXTex version of ``texconv.exe`` does not make use of Direct3D at all unless you are using the DirectX 11 era "BC6H" or "BC7" DirectCompute-based compression. Modern Direct3D has much better support for 'session 0' and 'secure desktop' in any case.

The DirectXTex version of ``texconv.exe`` can produce legacy D3DX9 compatible DDS files by using the ``-dx9`` switch.

Keep in mind the specific names of the ``-f`` formats uses the "DXGI_FORMAT" naming scheme and formats that is different than the legacy Direct3D SDK tool. The DirectXTex tool doesn't support some of the older formats for write, but does support them for reading.

**Comment by walbourn** [comment]
There is no distinct ``-mf`` vs. ``-if``. The ``-if`` setting is used for all filtering including mipmap filtering. A classic "box" filter is the default, and you also get it by using ``-if BOX`` or ``-if FANT``.

https://github.com/microsoft/DirectXTex/wiki/Texconv
