### ISSUE TITLE
Bug: LoadDDSTextureFromFile() and LoadDDSTextureFromFileEx() shift-wrap pixels

### ISSUE THREAD

**Issue by GlassBeaver** [microsoft/DirectXTex#277]
`LoadDDSTextureFromFile()` and `LoadDDSTextureFromFileEx()` "shift-wrap" pixels to the right (by 32 pixels in the sample image).
`LoadFromDDSFile()` works fine.

[Sample code](https://www.toptal.com/developers/hastebin/guxawusiqi.apache)

Texconv command used to convert to DDS: `texconv.exe -m 0 some.png`

![DXTEXTextureShiftWrapBug](https://user-images.githubusercontent.com/15961472/168478834-e16e9619-493d-4f40-a659-d9e8d1de6896.png)

**Original source file:**

 ![Warrior_body_parts_DefaultMaterial_BaseColor](https://user-images.githubusercontent.com/15961472/168479023-79f0d5ab-63f9-4bde-9096-fc61b64903f2.png)

**Comment by walbourn** [comment]
The problem is this line of code in your usage:

```
memcpy(pTextureDataBegin, ddsData.get(), dataLength);
```

You can't just do a straight memcpy of all the data as you have to respect the ``RowPitch`` required by Direct3D as returned in ``D3D12_PLACED_SUBRESOURCE_FOOTPRINT``. As you are already using D3DX12, you can use ``MemcpySubresource`` to replace just the ``memcpy``, or you can use the ``UpdateSubresources`` helper as I do in my [code example](https://github.com/microsoft/DirectXTK12/wiki/DDSTextureLoader).

**Comment by GlassBeaver** [comment]
Thanks, good to know about `MemcpySubresource()` and `UpdateSubresources()`.

**Comment by walbourn** [comment]
Also, be sure you are copying the image data from the return subresources array, NOT from the raw ``ddsData``. You are getting the DDS header content in your image data as well, which why you get the consistent offset. In this case, the RowPitch and the default DDS RowPitch just happen to be the same.
