### ISSUE TITLE
dec2022 causes _ITERATOR_DEBUG_LEVEL errors on ninja builds

### ISSUE THREAD

**Issue by vongkitt** [microsoft/DirectXTex#300]
Using `dec2022`, this will break non `MSVC` builds with an `_ITERATOR_DEBUG_LEVEL` error.

```
lld-link: error: /failifmismatch: mismatch detected for '_ITERATOR_DEBUG_LEVEL':

>>> XXXX.lib(XXXX.cxx.obj) has value 0

>>> DirectXTex.lib(DirectXTexCompress.cpp.obj) has value 2

clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Got this error using `ninja` and VS 17.4.3 using the `clang` toolchain
This change to `CMakeList.txt` did trigger it:

```
    foreach(t IN LISTS TOOL_EXES ITEMS ${PROJECT_NAME})
      target_compile_definitions(${t} PRIVATE $<IF:$<CONFIG:DEBUG>,_DEBUG,NDEBUG>)
    endforeach()
```

**Comment by walbourn** [comment]
Thanks for the feedback.

The CMake change is intentional. It was a bug that debug features were not enabled in the library in the Debug configuration for non-MSVC compilers. For the specific case of using clang/LLVM for Windows but *not* using the ``clang-cl`` driver, you should probably be explicitly defining ``_DEBUG`` for your debug builds in your code.

That said, I can see there are scenarios where a client of the library may want to disable iterator debugging in debug builds, so I've added a new build option for this.

**Comment by vongkitt** [comment]
This is still causing issue because it changes the linkage

```  
>>> XXXXXXX has value MD_DynamicRelease
>>> DirectXTex.lib(DirectXTexCompress.cpp.obj) has value MDd_DynamicDebug
  ```
