### ISSUE TITLE
R8G8_UNORM Incorrect Bitmasks in PixelFormat

### ISSUE THREAD

**Issue by Puxtril** [microsoft/DirectXTex#325]
I was doing some testing (printing out the PixelFormat struct for each DXGI_FORMAT), and noticed what seems to be an error. I looked at both `R8G8_UNORM` and `R8G8_SNORM`, which should have the same bit masks, but instead have this:

| Format | Red | Green| Blue | Alpha |
| ------- | ---- | ---- | ------- | ------ | 
| R8G8_UNORM | 0xff | 0x0 | 0x0 | 0xff00 |
| R8G8_SNORM | 0xff | 0xff00 | 0x0 | 0x0 |

**Comment by walbourn** [comment]
What source file are you looking in? (code line would help).

**Comment by Puxtril** [comment]
I haven't looked at the source code, I just downloaded the latest release (January 31, 2023) and ran the tool using a Python script that converts and prints the resulting PixelFormat struct.

**Comment by walbourn** [comment]
As in the DDS file header?

**Comment by Puxtril** [comment]
Correct, the PixelFormat struct inside the DDS Header.

This is the command I used: `.\texconv.exe -o .\output\ -f R8G8_UNORM .\sublime_text.png`
The command output:
```
reading .\sublime_text.png (512x512 R8G8B8A8_UNORM_SRGB 2D) as (512x512,10 R8G8_UNORM 2D)
writing .\output\sublime_text.dds
```
I've attached the resulting DDS file. (Zipped because Github doesn't like the .dds extension)
[sublime_text.zip](https://github.com/microsoft/DirectXTex/files/10925076/sublime_text.zip)

**Comment by walbourn** [comment]
OK. So the behavior you are seeing is due to the way modern DXGI_FORMAT values are 'mapped' to the legacy Direct3D 9 era DirectDraw PixelFormat header in a DDS. DirectXTex has a 'DX10' extension header that directly expresses the DXGI_FORMAT, but there are issues with that as well. See [this blog post](https://walbourn.github.io/the-dds-file-format-lives/). The array of legacy formats are in [DDS.h](https://github.com/microsoft/DirectXTex/blob/main/DirectXTex/DDS.h).

The ``DXGI_FORMAT_R8G8_UNORM`` format is mapped to the Direct3D 9 ``D3DFMT_A8L8`` format. In DDS files, this is:

```
DDSGLOBALCONST DDS_PIXELFORMAT DDSPF_A8L8 =
{ sizeof(DDS_PIXELFORMAT), DDS_LUMINANCEA, 0, 16, 0x00ff, 0, 0, 0xff00 };
```

The ``DXGI_FORMAT_R8G8_SNORM`` format is mapped to the Direct3D 9 ``D3DFMT_V8U8`` format. In DDS files, this is:

```
DDSGLOBALCONST DDS_PIXELFORMAT DDSPF_V8U8 =
{ sizeof(DDS_PIXELFORMAT), DDS_BUMPDUDV, 0, 16, 0x00ff, 0xff00, 0, 0 };
```

IOW: You need to look at the pixel flags and bit size, not just the channel masks.
