### ISSUE TITLE
ATI2N (BC5) Conversion failing with error 80070032

### ISSUE THREAD

**Issue by thrownewexception** [Microsoft/DirectXTex#34]
Not sure why this is erroring out... http://prnt.sc/c9kuy7 Visual Studio is able to properly open the image files...

**Comment by thrownewexception** [comment]
Also converting from a image to BC5_UNORM works but going out of it still fails.

**Comment by walbourn** [comment]
The command-line you provided is converting a DDS file (with the file format ``BC5_UNORM``) to try to write it as a TGA file. It knows it needs to uncompress the file because only DDS files can contain BC format data--hence why it's converting it to ``R8B8_UNORM``. The TGA format doesn't support that format for writing which is why you are getting an HRESULT of ERROR_NOT_SUPPORTED.

If you added a specific conversion format to the command-line, then it would be able to expand it a TGA:

    texconv -ft TGA -f R8G8B8A8_UNORM test.dds

Of course, that assumes you are wanting to go from DDS -> TGA. If you are trying to compress a TEST.TGA as a DDS, then you'd use:

    texconv -f BC5_UNORM test.tga
