### ISSUE TITLE
Support TGA color-mapped files with expansion

### ISSUE THREAD

**Issue by walbourn** [Microsoft/DirectXTex#38]
The current TGA loader does not support `TGA_COLOR_MAPPED` or `TGA_COLOR_MAPPED_RLE` images. Legacy D3DX9 did support them, but loaded them as `D3DFMT_P8` (i.e. 256-index palette).

While there are no palette DXGI formats, such TGA files could be expanded to `B5G5R5A1_UNORM` (`bColorMapSize` of 15 or of 16) or `R8G8B8A8_UNORM` (`bColorMapSize` of 24 or 32).

**Comment by walbourn** [comment]
There's generally not much call for color-mapped ``TGA`` files as their primary value is being able to encode 24bpp or 32bpp pixel data.

**Comment by dingsheng999** [comment]
Thanks a lot Chuck for this great library. I tested DirectXTex for .tga sample files on http://www.fileformat.info/format/tga/sample/index.htm, and only one file, 'CCM8.TGA', cannot be correctly decoded because it's a color-mapped TGA. It's still nice to have DirectXTex support this kind of file so that people can use it as a general TGA reader, and along with other awesome functions such as pixel format conversion.

**Comment by dingsheng999** [comment]
@walbourn I tried to search on Bing, Baidu, Google and a even a few image websites for professional artists but cannot find a single real case color-mapped TGA file. That sample file is the only one I can find.

**Comment by walbourn** [comment]
It seems like color-mapped TGAs just never got any real traction in the real world since other formats cover that scenario well. As such, I'm closing this issue.
