### ISSUE TITLE
Build /mt failed

### ISSUE THREAD

**Issue by ng0403** [microsoft/DirectXTex#397]
when i build DirectXTex_Windows10_2022 with /mt but returns msb8024.
Is there a solution?

**Comment by walbourn** [comment]
That solution/project is for building Universal Windows Platform apps, and they don't support static CRT linking. You need to use the dynamic CRT which is managed and maintained by the Microsoft Store.

For Win32 desktop, you could modify the project to use the static CRT if desired, although it's not recommended which is why all the vcxproj files are set to use `<RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>` or defaults to `<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>`.
