### ISSUE TITLE
(Question) Converting BC4 to BMP with texconv

### ISSUE THREAD

**Issue by hopperpl** [microsoft/DirectXTex#425]
When converting a BC4 (dds) texture to BMP, the WIC encoder by default creates a palette .bmp file. When I specify `-f rgba` then it generates an RGB image, but uses black/white coloring, meaning it sets all 3 channels red, green, and blue to the same value.

Contrary, when doing the same with a BC5 texture, red and green are set, while blue is zero.

Is there a way to let `texconv` similarly generate a .bmp file with only the red channel set, while green and blue are zero?

**Comment by walbourn** [comment]
The default decompress format for BC4 maps to ``DXGI_FORMAT_R8_UNORM`` which is a single red channel (BC4 encodes just one channel). When ``DXGI_FORMAT_R8_UNORM`` is passed to the WIC writer, the default format for WIC maps to ``GUID_WICPixelFormat8bppGray``. For the .BMP codec, this is written as a ``BI_RLE8`` which is a palette mode, and the BMP palette is the identity (0-255 maps to greyscale colors 0-255).

The default decompress format for BC5 maps to ``DXGI_FORMAT_R8G8_UNORM`` which is a two channel format (BC5 encodes two channels). When ``DXGI_FORMAT_R8G8_UNORM`` is passed to the WIC writer, there is no WIC format that exactly matches so that writer fails. Therefore, you have to provide the target format you want to use.

With that out the way, when you provide `-f rgba` the target format for the conversion becomes `` DXGI_FORMAT_R8G8B8A8_UNORM``.  The tool first decompresses BC4 to R8, then converts from R8 to R8G8B8A8. The default behavior for such conversions is to do a 'greyscale expansion' as you see.

If on the other hand you provide a BC5, then it decompresses to R8G8, then converts R8G8 to R8G8B8A8. The default behavior for such conversions is to copy R to red, G to green, and set B to zero, and A to 1.

From my understanding of your question, you want BC4 to write out to R8G8B8A8 where R is red, G is 0, B is zero, and A is 1. You can do this with the ``-swizzle`` option. In your case ``-swizzle r001`` which will copy the red channel and then set the other channels to fixed values.
