### ISSUE TITLE
MipMapCount == 0 ?

### ISSUE THREAD

**Issue by mikeeheler** [Microsoft/DirectXTex#43]
This is a question.

When converting textures to DDS using texconv, if you don't want mipmaps, you must specify -m 1. If you specify -m 0, the entire chain is generated and saved.

In the wild it is not uncommon to find DDS' which do not set DDS_HEADER_FLAGS_MIPMAP, and which set dwMipMapCount to 0.  DirectXTex seems to want to force the behaviour of always setting that flag, and always having a non-zero value for dwMipMapCount 

In DirectXTexDDS.cpp, in DecodeDDSHeader, if dwMipMapCount is 0, it is forced to 1. Then, in _EncodeDDSHeader, if dwMipMapCount is > 0, the DDS_HEADER_FLAGS_MIPMAP flag is set.

Should I take it as read, then, that mipmap-less (no flag, and dwMipMapCount == 0) is a deprecated DDS configuration?

**Comment by mikeeheler** [comment]
Adding to this I have also noticed the DDS_HEADER.dwCaps DDSCAPS_MIPMAP flag. DirectXTexDDS.cpp sets this flag if dwMipMapCount is > 1, a truly mipmapped texture, while it basically always sets DDS_HEADER_FLAGS_MIPMAP and sets DDS_HEADER.dwMipMapCount to 1 or more.

**Comment by walbourn** [comment]
The ``DDS`` file format is not particularly well specified. I have made sure the basics are on [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb943990.aspx), but it's largely a matter of trying to match "What does the legacy ``D3DX9``, ``D3DX10``, and/or ``D3DX11`` library do?". In some places where the original behavior was a little lose, I tried to be a bit more consistent with DirectXTex.

In the original ``D3DX9`` code it writes DDS headers as follows:

    DDS_HEADER Header;
    memset(&Header, 0x00, sizeof(DDS_HEADER));

    Header.dwSize   = sizeof(DDS_HEADER);
    Header.dwFlags  = DDS_DDSD_HEIGHT | DDS_DDSD_WIDTH | DDS_DDSD_PIXELFORMAT | DDS_DDSD_CAPS;
    Header.dwHeight = (DWORD) m_uHeight;
    Header.dwWidth  = (DWORD) m_uWidth;
    Header.ddpf     = pFormatDDPF->ddpf;
    Header.dwCaps   = DDS_CAPS_TEXTURE;

    if(pFormatDDPF->ddpf.dwFlags & (DDS_DDPF_ALPHAPIXELS | DDS_DDPF_ALPHA))
        Header.dwCaps |= DDS_CAPS_ALPHA;

    if(pFormatDDPF->ddpf.dwFlags & (DDS_DDPF_PALETTEINDEXED8))
        Header.dwCaps |= DDS_CAPS_PALETTE;

    if(m_pMip)
    {
        Header.dwFlags |= DDS_DDSD_MIPMAPCOUNT;
        Header.dwMipMapCount = (DWORD) uMipLevels;
        Header.dwCaps |= DDS_CAPS_COMPLEX | DDS_CAPS_MIPMAP;
    }

    if(m_pFace)
    {
        Header.dwCaps |= DDS_CAPS_COMPLEX;
        Header.dwCaps2 |= DDS_CAPS2_CUBEMAP | DDS_CAPS2_CUBEMAP_ALLFACES;
    }

    if(m_uDepth > 1)
    {
        Header.dwFlags |= DDS_DDSD_DEPTH;
        Header.dwDepth = (DWORD) m_uDepth;
        Header.dwCaps2 |= DDS_CAPS2_VOLUME;
    }

When reading DDS files, ``D3DX9`` does this with respect to the mipmaps:

    // Grok levels
    UINT cMipLevels;
    cMipLevels = (UINT) pHeader->dwMipMapCount;

    if(0 == cMipLevels)
        cMipLevels = 1

    // Attempting to skip all levels will load just the smallest level
    if (cSkipLevels >= cMipLevels)
        cSkipLevels = cMipLevels - 1;

The DirectXTex ``texconv``  behavior is also based on the legacy DirectX SDK command-line tool of the same name, which is why it defaults to generating all mipmaps (i.e. `` -m 0``) by default.

**Comment by mikeeheler** [comment]
Great! Thank you for the thorough response, Chuck. It's very appreciated.
