### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by daanzhu** [Microsoft/DirectXTex#44]
I try to build the solution with VS 2015, it gives me the error below.
==========================
1>  DirectXTexUtil.cpp
1>c:\program files (x86)\windows kits\8.1\include\um\wincodec.h(943): error C3646: 'PixelFormat': unknown override specifier
1>c:\program files (x86)\windows kits\8.1\include\um\wincodec.h(943): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
===========================
I had installed the DirectX SDK June 2010 on my PC. It seems, after I uninstalled the DirectX SDK, the build is fine. Why it conflicts to the DirectX SDK June 2010? Are there any way to walk around?

Thank you very much.
Dan

**Comment by walbourn** [comment]
The headers in the legacy DirectX SDK are older than the Windows 8 SDK headers which come with VS 2012 or later. Therefore, if you need the DirectX SDK, then you must *reverse* the include & library path order so that the Windows SDK content comes before the legacy DirectX SDK. Otherwise you can end up with a mix of old and new headers which don't build.

See [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275.aspx), [Where is the DirectX SDK (2015 Edition)?](https://blogs.msdn.microsoft.com/chuckw/2015/08/05/where-is-the-directx-sdk-2015-edition/), and [The Zombie DirectX SDK](https://blogs.msdn.microsoft.com/chuckw/2015/03/23/the-zombie-directx-sdk/).

The standard vcxproj files in the DirectXTex packages do not use the legacy DirectX SDK anymore, so I don't know how those paths ended up in your build setup, but you should check that.
