### ISSUE TITLE
Using DXTex to save and load PNGs with SRGB

### ISSUE THREAD

**Issue by jules43** [Microsoft/DirectXTex#49]
I have a code generated texture which I save to a file and then reload.

The sequence is:
  Generate image data
  SaveToWICFile
  LoadFromWICFile
  Use image data

When I do this saving to a PNG the data comes back having had some sort of gamma transformation applied to it.

If I use SaveToDDSFile / LoadFromDDSFile then the gamma transformation does not occur.

If I set the WIC_FLAGS_IGNORE_SRGB on the call to LoadFromWICFile then the gamma transformation also does not occur.

My internal pixel format is DXGI_FORMAT_R8G8B8A8_UNORM but I'm converting to DXGI_FORMAT_B8G8R8A8_UNORM before saving as this appears to result in more widely supported PNG files.

If I set the format to DXGI_FORMAT_B8G8R8A8_UNORM_SRGB then this doesn't seem to have any affect either way.

It seems like Save then Load of any particular format should always produce nearly the same result which does not appear to be the case.

Is this a bug or is this the intended behaviour?

My data is effectively SRGB, so I want it to be saved in and loaded untransformed. What is the correct way to achieve this?

Thanks

**Comment by walbourn** [comment]
The WIC loader is checking for the presence of a sRGB colorspace chunk and if the image has it, it returns an ``_SRGB`` version of the format. When writing PNGs, the default behavior of WIC is to write the sRGB colorspace chunk. I have an outstanding [pull request](https://github.com/Microsoft/DirectXTex/pull/48) I'm reviewing for how I should handle the default behavior. Likely I'll change it so that it does not put in the chunk unless you write an ``_SRGB`` format.

**Comment by jules43** [comment]
With the way the API functions at the moment is there a more correct way to handle this scenario than to set the WIC_FLAG_IGNORE_SRGB on Load?

Can one set the WIC_FLAG_IGNORE_SRGB flag when writing to cause it to not write the sRGB chunk?

**Comment by walbourn** [comment]
I need to update the library writer to use that flag, but that's likely the plan.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXTex/commit/211d96003452c1deb1aca4445acc05e502e8b7d7)
