### ISSUE TITLE
Unsupported TGA file

### ISSUE THREAD

**Issue by LautrecOfCarim** [Microsoft/DirectXTex#50]
I'm having problems with one .tga file (attached), texconv.exe fails to read it. It opens normally with paint.net and I'm not sure what the problem is.

```
F:\DirectXTex-master\Texconv\Bin\Desktop_2017\Win32\Debug>texconv.exe bad_file.tga
Microsoft (R) DirectX Texture Converter (DirectXTex version)
Copyright (C) Microsoft Corp. All rights reserved.
*** Debug build ***

reading bad_file.tga FAILED (80070032)

F:\DirectXTex-master\Texconv\Bin\Desktop_2017\Win32\Debug>
```

[bad_file.zip](https://github.com/Microsoft/DirectXTex/files/921876/bad_file.zip)

**Comment by walbourn** [comment]
I have a little utility for dumping out the header information I use for debugging purposes (found [here](https://raw.githubusercontent.com/wiki/Microsoft/DirectXTex/tgadump.cpp)). For your file it outputs:

    TGA bad_file.tga
    ColorMap Type = 1
    ImageType = 1   TGA_COLOR_MAPPED
    ColorMap First = 0
    ColorMap Length = 256
    ColorMap Entry Size = 24
    Origin 0, 0
    Size: 4096 by 4096
    Bits Per Pixel 8
    Image descriptor 00
    ExtensionOffset = 0
    DeveloperOffset = 0
    Signature= TRUEVISION-XFILE.

As noted on the [wiki](https://github.com/Microsoft/DirectXTex/wiki/TGA-I-O-Functions#implementation-notes) the ``TGA`` reader does not support color-mapped (i.e. palette) files which are uncommon for ``TGA`` (since the main value of that format is being able to encode 24bpp images). I do have an open issue for a possible way to handle them since there are no paletted DXGI formats. See [38](https://github.com/Microsoft/DirectXTex/issues/38)
