### ISSUE TITLE
DXGI_FORMAT_BC1_UNORM_SRGB to DXGI_FORMAT_BC1_UNORM and back

### ISSUE THREAD

**Issue by revcarl** [Microsoft/DirectXTex#72]
Hi, I am a modder using resorep which is a DirectX 11 texture replacer in order to recolor textures and load them back in game. The problem is only Photoshop has a dds plugin that takes advantage of the latest image compression methods (BCn/DXT)  I am trying to figure out how to convert the DXGI_FORMAT_BC1_UNORM_SRGB to DXGI_FORMAT_BC1_UNORM so I can load it in paint.net and then convert it back to its original state so it hopefully loads in game. I asked the question last year here: https://github.com/Microsoft/DirectXTex/issues/52 but I wasn't very detailed. I was able to convert it back so it loaded in Photoshop but like I said with lighter colors. I used the advice you gave me but my Photoshop trial was over so I couldn't look at it to see how it worked out but it didn't load in game anyway like it would if I had only used Photoshop.  Here is an example of export settings for the original retrieved texture that can only be opened in Photoshop (sRGB)
![dxgi_format_bc1_unorm_srgb](https://user-images.githubusercontent.com/11702180/34901812-57037f80-f7c4-11e7-8e4c-3bfe6d3c9a5d.png)
and here is an example for retrieved textures I can open in paint.net
![dxgi_format_bc1_unorm](https://user-images.githubusercontent.com/11702180/34901820-7065ca1e-f7c4-11e7-9d75-9314d0a555af.png)
So I am just wondering if this is possible using this tool and if so how.
By the way I am using TexConv but I also have Texassemble and Texdiag if needed for some reason.
Thanks for your time and all the help
RevCarl

**Comment by walbourn** [comment]
It all really depends on the application that's consuming the ``DDS`` filesas to how they interepret the colorspace. If it's an old game or a DirectX 9 game, it might not even recognize the ``DX10`` header extension format required for the explicit ``SRGB`` version of the format (that's why that tool says "DX10+" in the combo box).

ThHe ``texconv`` tool has ``srgbi`` and ``srgbo`` switches to do various tricks with how it handles the SRGB conversion, but you really just have to play aroun with all the posssibilties to work out what's happening.

**Comment by revcarl** [comment]
thank you for your reply
