### ISSUE TITLE
Fails to compress non-pow2 BC6H volume texture

### ISSUE THREAD

**Issue by redorav** [Microsoft/DirectXTex#89]
I'm trying to compress a BC6H volume texture that is not a power of 2. If I set the mips to -m 0 it works fine, presumably because this is automatic mip creation and it tries to create the full mipchain but can only do the first mip. However, a pow2 volume texture will have all its mip created, which is not what I want.

If I set -m 1, then the pow2 texture correctly creates just one mip, but the non-pow2 fails to compress even though I have specifically requested just one mip. Basically I find this to be inconsistent behavior.

I can make it work by replacing this bit of code

```cpp
if (info.dimension == TEX_DIMENSION_TEXTURE3D)
{
    if (!tMips)
    {
        tMips = 1;
    }
```

with

```cpp
if (info.dimension == TEX_DIMENSION_TEXTURE3D)
{
    if (tMips <= 1)
    {
        tMips = 1;
    }
```

Do you think this is a good fix? Any chance of merging it in? I would create a PR but for some reason I can't pull the repo in at work.

**Comment by walbourn** [comment]
The ``texconv`` tool tries to create mipmaps by default. ``-m 0`` is the same as not providing an ``-m`` parameter. If you want to disable the generation of mips you use ``-m 1``. I'm mimicking the behavior of the legacy DirectX SDK ``texconv`` tool here.

As noted in the output, I don't support mipmap generation of non-power-of-2 volume textures because Direct3D does not support mipmapped non-power-of-2 volume textures.

        if (!ispow2(info.width) || !ispow2(info.height) || !ispow2(info.depth))
        {
            if (info.dimension == TEX_DIMENSION_TEXTURE3D)
            {
                if (!tMips)
                {
                    tMips = 1;
                }
                else
                {
                    wprintf(L"\nERROR: Cannot generate mips for non-power-of-2 volume textures\n");
                    return 1;
                }
            }
            else if (!tMips || info.mipLevels != 1)
            {
                nonpow2warn = true;
            }
        }

Direct3D does have non-power-of-2 texture mipmap support for 2D textures for Direct3D Hardware Feature Level 10.0 or better. For Direct3D Hardware Feature Level 9.x, only non-power-of-2 textures without mipmaps are supported. See [Direct3D feature levels](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476876.aspx)

**Comment by redorav** [comment]
> If you want to disable the generation of mips you use -m 1.

That's what I'm doing, but texconv refuses to compress a non-pow2 texture if I set the flag to 1, even though I'm telling it I don't want any mips.

**Comment by walbourn** [comment]
Ah, yes, I see it now :)

> BTW, ``GenerateMipMaps3D`` will let you create mipmaps for a non-power-of-2 texture through the ``TEX_FILTER_TRIANGLE``, but I don't support it through ``texconv`` because I don't believe Direct3D supports this scenario.

Let me do a little testing here because apparently I've not got this case covered in my tests.

**Comment by walbourn** [comment]
So on Direct3D Feature Level 10.0 or better, you can create non-power-of-2 mipmapped volume textures. Of course, only the TRIANGLE filter actually results in a meaningful mipmap chain for non-power-of-2 depth. I need to revisit the logic here or do what my code originally intended which is to let you use ``-m 1`` for non-pow2 volume textures.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXTex/commit/90a34e9959a3ae402f8d9fe447f5664665f33b1e)
